### PR TITLE
Rails 5.0 support

### PR DESCRIPTION
**Pull request by NickLaMuro**
Bump gemspec requirement to allow for Rails 5.0 and add tests for new version of Rails.

### CODE REVIEW

**Comment by NickLaMuro** [comment]
@BookOfGreg Again, thanks for the help on getting the tests to pass for 5.0!  I have merged in your changes and added a few others as well to get the tests passing for the other builds.

A note about the final commit:  because of the `mime-types` dependency issue, bundler seems to go with `2.99` for all Rails-4.0 and Rails.4.1 builds instead of using the latest release, even on non-1.9.3 builds.  I don't see that being a big deal as far as running the test suite, but it should be noted none the less.

**Comment by fixlr** [comment]
@NickLaMuro @BookOfGreg Thanks for tracking down the causes of these failures! I'm going to add https://github.com/fixlr/codemirror-rails/commit/8aada52c06018ed09166c65c07939904fea5c6c5 too, to use a newer `mime-types` on the versions of Ruby that support it. The `platforms` options doesn't actually allow Bundler to resolve two _different_ versions of a gem, so I added separate gemfiles for that.

**Comment by fixlr** [comment]
Merged, despite what GitHub thinks. :)

**Comment by NickLaMuro** [comment]
@fixlr Thanks for getting this in!  Glad to help!

**Pull request closed without merging**
